# -*- coding: utf-8 -*-
"""CS4403_lab02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqA7AYhUc88i9KmpIbBENPPUioq3-sMv
"""

import random
import matplotlib.pyplot as plt
import numpy as np
import time 
import pandas as pd
from scipy.stats import gaussian_kde
import seaborn as sns
import csv

data = pd.read_csv('Monthly_agv_p.csv')
data.plot(figsize=(10, 8))
plt.xlim(0,400)
plt.legend(loc="upper left")

data = pd.read_csv('Monthly_agv_p.csv')
data.hist(range=[0, 250],figsize=(15, 10))

data = pd.read_csv('Tick_Data.csv')
data.hist(figsize=(10, 10))

F2010count=0
F2011count=0
F2012count=0
F2013count=0
F2014count=0
F2015count=0
F2016count=0
F2017count=0
F2018count=0
F2019count=0
F2020count=0

M2010count=0
M2011count=0
M2012count=0
M2013count=0
M2014count=0
M2015count=0
M2016count=0
M2017count=0
M2018count=0
M2019count=0
M2020count=0

data = pd.read_csv('Tick_Data.csv', usecols=['SEX / SEXE','YEAR / ANNÉE'])
for i in range(0,len(data)):
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2010:
     F2010count=F2010count+1
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2011:
     F2011count=F2011count+1 
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2012:
     F2012count=F2012count+1
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2013:
     F2013count=F2013count+1 
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2014:
     F2014count=F2014count+1
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2015:
     F2015count=F2015count+1 
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2016:
     F2016count=F2016count+1
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2017:
     F2017count=F2017count+1           
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2018:
     F2018count=F2018count+1
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2019:
     F2019count=F2019count+1 
  if data.iloc[i]["SEX / SEXE"] =="F" and data.iloc[i]["YEAR / ANNÉE"] == 2020:
     F2020count=F2020count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2010:
     M2010count=M2010count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2011:
     M2011count=M2011count+1 
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2012:
     M2012count=M2012count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2013:
     M2013count=M2013count+1 
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2014:
     M2014count=M2014count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2015:
     M2015count=M2015count+1 
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2016:
     M2016count=M2016count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2017:
     M2017count=M2017count+1           
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2018:
     M2018count=M2018count+1
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2019:
     M2019count=M2019count+1 
  if data.iloc[i]["SEX / SEXE"] =="M" and data.iloc[i]["YEAR / ANNÉE"] == 2020:
     M2020count=M2020count+1

Flist = []
Flist.append(F2010count)
Flist.append(F2011count)
Flist.append(F2012count)
Flist.append(F2013count)
Flist.append(F2014count)
Flist.append(F2015count)
Flist.append(F2016count)
Flist.append(F2017count)
Flist.append(F2018count)
Flist.append(F2019count)
Flist.append(F2020count)
print(Flist)
Mlist = []
Mlist.append(M2010count)
Mlist.append(M2011count)
Mlist.append(M2012count)
Mlist.append(M2013count)
Mlist.append(M2014count)
Mlist.append(M2015count)
Mlist.append(M2016count)
Mlist.append(M2017count)
Mlist.append(M2018count)
Mlist.append(M2019count)
Mlist.append(M2020count)
print(Mlist)
plt.figure(figsize=(15, 10))
plt.title("Number of Female and Male bitten by ticks, 2010 - 2022 each year")
FemaleX = ['F2010','F2011','F2012','F2013','F2014','F2015','F2016','F2017','F2018','F2019','F2020']
MaleX = ['M2010','M2011','M2012','M2013','M2014','M2015','M2016','M2017','M2018','M2019','M2020']
plt.bar(FemaleX,Flist,color='pink',label="Female")
plt.bar(MaleX,Mlist,color='skyblue',label="Male")
plt.legend()
plt.show()

import random
import matplotlib.pyplot as plt
import numpy as np
import time 
import pandas as pd
from scipy.stats import gaussian_kde
import seaborn as sns
import csv

data = pd.read_csv('Monthly_agv_p.csv')
data.boxplot(color=dict(boxes='g', whiskers='b', medians='y', caps='r'))
