# -*- coding: utf-8 -*-
"""lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6Gde4OKMgwBzp_YO1GEWOTC-cpWujlZ
"""

import random

for i in range(0,201):
    random.seed(i)
    num = random.randint(1000000, 9999999)
    print(num)
    lastTwo = num%100
    a= lastTwo//10
#    print("a",a)
    b = lastTwo%10
#    print("b",b)
    if a == b:
       print("seed =",i ,"has equal last two number")