# -*- coding: utf-8 -*-
"""lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6Gde4OKMgwBzp_YO1GEWOTC-cpWujlZ
"""

import random
import matplotlib.pyplot as plt
import numpy as np
Tlist = []
count = 0
for i in range(1,202):
    random.seed(i)
    num = random.randint(1000000, 9999999)
#    print(num)
    lastTwo = num%100
    a= lastTwo//10
#    print("a",a)
    b = lastTwo%10
#    print("b",b)
    if a == b:
       count = count+1
       Tlist.append(i)
       print("Seed =",i ,", Random Number =",num,"has equal last two number")
y = np.arange(count) 
plt.scatter(Tlist, y)
plt.title("Scatter Plot Of times")
plt.xlabel('Seeds')
plt.ylabel('Times')
 
plt.show()