# -*- coding: utf-8 -*-
"""lab_lastThree

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hB5p0QAzTiCGHn3usXQkYEQr0dw24P2X
"""

import random
import matplotlib.pyplot as plt
import numpy as np
Tlist = []
count = 0
for i in range(1,202):
    random.seed(i)
    num = random.randint(1000000, 9999999)
    lastThree = num%1000
    lastTwo = num%100
    c = lastThree//100
    a= lastTwo//10
    b = lastTwo%10
    if a == b == c:
       count = count+1
       Tlist.append(i)
       print("Seed =",i ,", Random Number =",num,"has equal last three number")
y = np.arange(count) 
plt.scatter(Tlist, y)
plt.title("Scatter Plot Of times")
plt.xlabel('Seeds')
plt.ylabel('Times')
 
plt.show()
