# -*- coding: utf-8 -*-
"""lab1_lastTwo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6Gde4OKMgwBzp_YO1GEWOTC-cpWujlZ
"""

import random
import matplotlib.pyplot as plt
import time 
import numpy as np
Tlist = []
count = 0
cCount =0
cCountSum = 0
for i in range(1,202):
    start = time.time()
    cCount = cCount + 1
    random.seed(i)
    num = random.randint(1000000, 9999999)
    lastTwo = num%100
    a= lastTwo//10
    b = lastTwo%10
    if a == b:
       cCountSum= cCountSum+cCount
       count = count+1
       Tlist.append(i)
       print("Seed =",i ,", Random Number =",num,"has equal last two number")
       cCount = 0
    end = time.time()    
print('running time: ',(end - start))
print('average number of iterations required before a collision: ', cCountSum/count)
y = np.arange(count) 
plt.scatter(Tlist, y)
plt.title("Scatter Plot Of times")
plt.xlabel('Seeds')
plt.ylabel('Times')
 
plt.show()
